a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

 print("Modulo Division:", a % b)
 print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Modulo Division:", a % b)
print("Floor Division:", a // b)
